name: my-workspace
version: "3"

services:
  code_server:
    build:
      context: .
      dockerfile: .docker/code_server/Dockerfile
    ports:
      - "8443:8443"
    environment:
      - TZ=UTC
      - HOME=/config
      - SUDO_PASSWORD=casaos
      - DEFAULT_WORKSPACE=/config #optional
    volumes:
      - ./config:/config
    container_name: code_server
  ssh:
    build:
      context: .
      dockerfile: .docker/openssh/Dockerfile
      args:
        - USERNAME=casaos
        - USER_PASSWORD=casaos
        - DEFAULT_WORKSPACE=/config #optional
    ports:
      - "2222:22"   #SSH
    environment:
      - TZ=UTC
      - HOME=/root
    volumes:
      - ./config:/config
    container_name: my_workspace_ssh