name: my-workspace
version: "3"

services:
  code_server:
    image: ghcr.io/ciuffetelli/myworkspace/code-server:latest
    ports:
      - "8443:8443"
    environment:
      - TZ=UTC
      - HOME=/config
      - SUDO_PASSWORD=casaos
      - DEFAULT_WORKSPACE=/config #optional
    volumes:
      - ./config:/config
    container_name: my_workspace_code_server
  ssh:
    image: ghcr.io/ciuffetelli/myworkspace/open-ssh:latest
    ports:
      - "2222:22"   #SSH
    environment:
      - TZ=UTC
      - HOME=/root
      - USERNAME=casaos
      - USER_PASSWORD=casaos
      - DEFAULT_WORKSPACE=/config #optional
    volumes:
      - ./config:/config
    container_name: my_workspace_ssh